exports.profile = require('./getProfile');
exports.logout = require('./getLogout');
exports.userJobs = require('./getJobs'); // why rename!
exports.signup = require('./signup');
exports.addJob = require('./postJob');
exports.services = require('./getServices');
exports.oneService = require('./getOneService');
exports.login = require('./login');
exports.isAuth = require('./auth');
